### ISSUE TITLE
Idea for icons...

### ISSUE THREAD

**Issue by alextappin** [new-dev/Tabrir#1]
http://www.google.com/s2/favicons?domain=www.google.com

This API returns the websites favicon (little image). We can use this for style.

**Comment by alextappin** [comment]
![image](https://cloud.githubusercontent.com/assets/7875255/12863048/11db6d9e-cc26-11e5-9003-bae113c79e7f.png)
Here is an image of an example... Something like this maybe?

**Comment by timothyjamesjensen** [comment]
I will make an icon.service to accomplish this

**Comment by alextappin** [comment]
is this working right now? Can we close this?
