### ISSUE TITLE
Create 'new group' template view

### ISSUE THREAD

**Issue by timothyjamesjensen** [new-dev/Tabrir#4]
When a user clicks 'new group' from the primary view, they should come to this view. this view will have the following:
- Name Field
  - 
- Url field
  - we can handlel multiple url's one of two ways
    1. automatically create a new field when text is entered
    2. have a small '+' button below the bottom most url field that allows the user to add more url's(i like this idea better)

These are the most basic features that we need in order to move forward. Later we will add much more functionality like little red exclamations points if the url is not valid etc

**Comment by timothyjamesjensen** [comment]
I really like option 'b' for how we can handle multiple url's. I think it provides us with much more functionality as the developers. its so much easier to work with. and we can demand that they make the previous url valid before we let them add another

**Comment by alextappin** [comment]
I believe my updates have satisfied this requirement. _Closed_
